# Generated by Django 6.0.2 on 2026-02-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('paginas', models.PositiveIntegerField()),
                ('editorial', models.CharField(max_length=40)),
            ],
        ),
    ]
