# Generated by Django 6.0.2 on 2026-03-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='tipo_error',
            field=models.CharField(max_length=100),
        ),
    ]
