# Generated by Django 6.0.2 on 2026-03-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiLibrosRestFrame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AddField(
            model_name='libroo',
            name='foto_binaria',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
